/**
 * This file was generated by the @pikku/cli
 */
import { pikkuState } from '@pikku/core'
pikkuState('rpc', 'meta', {
  "progressiveEnhancementExample": "progressiveEnhancementExample",
  "timeSinceOpened": "timeSinceOpened",
  "welcomeToPikku": "welcomeToPikku",
  "helloWorld": "helloWorld",
  "rpcTest": "rpcTest",
  "rpcCaller": "rpcCaller"
})