/**
 * This file was generated by @pikku/cli@0.11.2
 */
import { pikkuState } from '@pikku/core'
pikkuState('channel', 'meta', {
  "progressive-enhancement": {
    "name": "progressive-enhancement",
    "route": "/status/websocket",
    "input": null,
    "connect": null,
    "disconnect": null,
    "message": null,
    "messageWirings": {
      "action": {
        "status": {
          "pikkuFuncName": "progressiveEnhancementExample"
        }
      }
    }
  }
})