/**
 * This file was generated by the @pikku/cli
 */
import { pikkuState } from '@pikku/core'
pikkuState('function', 'meta', {
  "progressiveEnhancementExample": {
    "pikkuFuncName": "progressiveEnhancementExample",
    "inputSchemaName": null,
    "outputSchemaName": "ProgressiveEnhancementExampleOutput"
  },
  "timeSinceOpened": {
    "pikkuFuncName": "timeSinceOpened",
    "inputSchemaName": null,
    "outputSchemaName": "TimeSinceOpenedOutput"
  },
  "welcomeToPikku": {
    "pikkuFuncName": "welcomeToPikku",
    "inputSchemaName": null,
    "outputSchemaName": "string"
  },
  "helloWorld": {
    "pikkuFuncName": "helloWorld",
    "inputSchemaName": null,
    "outputSchemaName": "string"
  },
  "rpcTest": {
    "pikkuFuncName": "rpcTest",
    "inputSchemaName": "RpcTestInput",
    "outputSchemaName": null,
    "expose": true
  },
  "rpcCaller": {
    "pikkuFuncName": "rpcCaller",
    "inputSchemaName": "RpcCallerInput",
    "outputSchemaName": null
  }
})