/**
 * This file was generated by the @pikku/cli
 */
import { pikkuState } from '@pikku/core'
pikkuState('function', 'meta', {
  "progressiveEnhancementExample": {
    "pikkuFuncName": "progressiveEnhancementExample",
    "name": "progressiveEnhancementExample",
    "services": {
      "optimized": false,
      "services": []
    },
    "inputSchemaName": null,
    "outputSchemaName": "ProgressiveEnhancementExampleOutput",
    "inputs": [],
    "outputs": [
      "ProgressiveEnhancementExampleOutput"
    ],
    "isDirectFunction": true
  },
  "timeSinceOpened": {
    "pikkuFuncName": "timeSinceOpened",
    "name": "timeSinceOpened",
    "services": {
      "optimized": true,
      "services": [
        "channel"
      ]
    },
    "inputSchemaName": null,
    "outputSchemaName": "TimeSinceOpenedOutput",
    "inputs": [],
    "outputs": [
      "TimeSinceOpenedOutput"
    ],
    "isDirectFunction": true
  },
  "welcomeToPikku": {
    "pikkuFuncName": "welcomeToPikku",
    "name": "welcomeToPikku",
    "services": {
      "optimized": true,
      "services": []
    },
    "inputSchemaName": null,
    "outputSchemaName": "string",
    "inputs": [],
    "outputs": [
      "string"
    ],
    "isDirectFunction": true
  },
  "helloWorld": {
    "pikkuFuncName": "helloWorld",
    "name": "helloWorld",
    "services": {
      "optimized": true,
      "services": []
    },
    "inputSchemaName": null,
    "outputSchemaName": "string",
    "inputs": [],
    "outputs": [
      "string"
    ],
    "isDirectFunction": true
  },
  "rpcTest": {
    "pikkuFuncName": "rpcTest",
    "name": "rpcTest",
    "services": {
      "optimized": true,
      "services": [
        "logger",
        "rpc"
      ]
    },
    "inputSchemaName": "RpcTestInput",
    "outputSchemaName": null,
    "inputs": [
      "RpcTestInput"
    ],
    "outputs": [],
    "expose": true,
    "isDirectFunction": false
  },
  "rpcCaller": {
    "pikkuFuncName": "rpcCaller",
    "name": "rpcCaller",
    "services": {
      "optimized": true,
      "services": [
        "rpc"
      ]
    },
    "inputSchemaName": "RpcCallerInput",
    "outputSchemaName": null,
    "inputs": [
      "RpcCallerInput"
    ],
    "outputs": [],
    "isDirectFunction": true
  }
})